apiVersion: logging.kubesphere.io/v1alpha2
kind: Output
metadata:
  name: syslog
  namespace: kubesphere-logging-system
  labels:
    logging.kubesphere.io/enabled: "true"
    logging.kubesphere.io/component: logging
spec:
  matchRegex: (?:kube|service)\.(.*)
  syslog:
    host: syslog服务器或ip地址
    port: 端口
    mode: 所需的传输类型tls,tcp,udp
    syslogFormat: 需要使用的syslog格式rfc3164或者rfc5424
    syslogMaxSize: 每条消息允许的最大大小
    