apiVersion: logging.kubesphere.io/v1alpha2
kind: Output
metadata:
  name: syslog
  namespace: kubesphere-logging-system
  labels:
    logging.kubesphere.io/enabled: "true"
    logging.kubesphere.io/component: logging
spec:
  matchRegex: (?:kube|service)\.(.*)
  syslog:
    host: 192.168.0.1 #domain or IP address of the remote Syslog server.
    port: 514 #TCP or UDP port of the remote Syslog server.
    mode: tcp #Mode of the desired transport type, the available options are tcp, tls and udp.
    syslogFormat: rfc3164 #protocol format to use, the available options are rfc3164 and rfc5424.
    